name: Deploy Production
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS 18 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build
        run: npm i && npm run build
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: ./frontend/dist
          bucket: '${{ secrets.S3_BUCKET }}'
          bucket-region: '${{ secrets.S3_BUCKET_REGION }}'
          dist-id: '${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}'
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true